// Introspection-based schema dumper (no pg_dump/Docker required).
// Reads production's `prp` + `public` schemas via pg_catalog/information_schema
// (prp_* views in public depend on tables living in the legacy `prp` schema)
// and emits a single idempotent SQL file that can be applied to a fresh DB.
import fs from "fs";
import pg from "pg";

const envText = fs.readFileSync("C:\\Users\\asus\\OneDrive\\work\\IRPAPP\\DEv\\.env.local", "utf8");
const env = {};
for (const line of envText.split("\n")) {
  const m = line.match(/^([A-Z0-9_]+)=(.*)$/);
  if (m) env[m[1]] = m[2].trim().replace(/^["']|["']$/g, "");
}

const SCHEMAS = ["prp", "public"];

const client = new pg.Client({
  host: "aws-1-us-west-2.pooler.supabase.com",
  port: 5432,
  user: "postgres.kusuoxwzdxfuybvyiakg",
  password: env.SUPABASE_DB_PASSWORD,
  database: "postgres",
  ssl: { rejectUnauthorized: false },
});

await client.connect();
const q = (sql, params) => client.query(sql, params).then((r) => r.rows);

const out = [];
const section = (title) => out.push(`\n-- ============================================================\n-- ${title}\n-- ============================================================\n`);

let totalTables = 0, totalViews = 0, totalFunctions = 0, totalTriggers = 0, totalPolicies = 0;

// ---------- Extensions (schema-independent, once) ----------
section("EXTENSIONS");
const extensions = await q(`select extname from pg_extension where extname <> 'plpgsql' order by 1`);
for (const e of extensions) {
  out.push(`CREATE EXTENSION IF NOT EXISTS "${e.extname}" WITH SCHEMA extensions;`);
}

for (const SCHEMA of SCHEMAS) {
  section(`SCHEMA "${SCHEMA}"`);
  out.push(`CREATE SCHEMA IF NOT EXISTS "${SCHEMA}";`);

  // ---------- Enums / custom types ----------
  const enums = await q(
    `select t.typname, array_agg(e.enumlabel order by e.enumsortorder) labels
     from pg_type t
     join pg_enum e on e.enumtypid = t.oid
     join pg_namespace n on n.oid = t.typnamespace
     where n.nspname = $1
     group by t.typname order by 1`,
    [SCHEMA]
  );
  for (const en of enums) {
    const labels = en.labels.map((l) => `'${l.replace(/'/g, "''")}'`).join(", ");
    out.push(`DO $$ BEGIN\n  CREATE TYPE "${SCHEMA}"."${en.typname}" AS ENUM (${labels});\nEXCEPTION WHEN duplicate_object THEN NULL; END $$;`);
  }

  // ---------- Sequences (all — including those backing legacy serial columns) ----------
  const sequences = await q(
    `select c.relname
     from pg_class c
     join pg_namespace n on n.oid = c.relnamespace
     where c.relkind = 'S' and n.nspname = $1
     order by 1`,
    [SCHEMA]
  );
  for (const s of sequences) {
    out.push(`CREATE SEQUENCE IF NOT EXISTS "${SCHEMA}"."${s.relname}";`);
  }

  // ---------- Tables ----------
  const tables = await q(
    `select c.relname
     from pg_class c
     join pg_namespace n on n.oid = c.relnamespace
     where c.relkind = 'r' and n.nspname = $1
     order by c.relname`,
    [SCHEMA]
  );
  totalTables += tables.length;

  for (const t of tables) {
    const cols = await q(
      `select a.attname as name,
              format_type(a.atttypid, a.atttypmod) as type,
              a.attnotnull as notnull,
              pg_get_expr(ad.adbin, ad.adrelid) as default_expr,
              a.attidentity as identity,
              a.attgenerated as generated
       from pg_attribute a
       left join pg_attrdef ad on ad.adrelid = a.attrelid and ad.adnum = a.attnum
       where a.attrelid = ('"' || $1 || '"."' || $2 || '"')::regclass
         and a.attnum > 0 and not a.attisdropped
       order by a.attnum`,
      [SCHEMA, t.relname]
    );

    const colDefs = cols.map((c) => {
      let def = `  "${c.name}" ${c.type}`;
      if (c.generated === "s") {
        def += ` GENERATED ALWAYS AS (${c.default_expr}) STORED`;
      } else if (c.identity === "d") def += " GENERATED BY DEFAULT AS IDENTITY";
      else if (c.identity === "a") def += " GENERATED ALWAYS AS IDENTITY";
      else if (c.default_expr) def += ` DEFAULT ${c.default_expr}`;
      if (c.notnull) def += " NOT NULL";
      return def;
    });

    out.push(`CREATE TABLE IF NOT EXISTS "${SCHEMA}"."${t.relname}" (\n${colDefs.join(",\n")}\n);`);
  }

  // ---------- Sequence ownership (for legacy serial-style columns) ----------
  const seqOwnership = await q(
    `select s.relname as seq, t.relname as tbl, a.attname as col
     from pg_class s
     join pg_depend d on d.objid = s.oid and d.deptype = 'a'
     join pg_class t on t.oid = d.refobjid
     join pg_attribute a on a.attrelid = t.oid and a.attnum = d.refobjsubid
     join pg_namespace n on n.oid = s.relnamespace
     where s.relkind = 'S' and n.nspname = $1
     order by 1`,
    [SCHEMA]
  );
  for (const so of seqOwnership) {
    out.push(`ALTER SEQUENCE "${SCHEMA}"."${so.seq}" OWNED BY "${SCHEMA}"."${so.tbl}"."${so.col}";`);
  }

  // ---------- Primary keys + unique + check constraints (no FKs yet) ----------
  const constraints = await q(
    `select conname, contype, conrelid::regclass::text as tbl, pg_get_constraintdef(oid) as def
     from pg_constraint
     where connamespace = (select oid from pg_namespace where nspname = $1)
       and contype in ('p','u','c')
     order by contype, conname`,
    [SCHEMA]
  );
  for (const c of constraints) {
    out.push(`ALTER TABLE ${c.tbl} ADD CONSTRAINT "${c.conname}" ${c.def};`);
  }

  // ---------- Foreign keys (separate pass, after all tables in this schema exist) ----------
  const fks = await q(
    `select conname, conrelid::regclass::text as tbl, pg_get_constraintdef(oid) as def
     from pg_constraint
     where connamespace = (select oid from pg_namespace where nspname = $1)
       and contype = 'f'
     order by conname`,
    [SCHEMA]
  );
  for (const c of fks) {
    out.push(`ALTER TABLE ${c.tbl} ADD CONSTRAINT "${c.conname}" ${c.def};`);
  }

  // ---------- Indexes (excluding those backing constraints already created) ----------
  const indexes = await q(
    `select indexname, indexdef
     from pg_indexes
     where schemaname = $1
     order by indexname`,
    [SCHEMA]
  );
  const constraintNames = new Set(constraints.map((c) => c.conname).concat(fks.map((c) => c.conname)));
  for (const idx of indexes) {
    if (constraintNames.has(idx.indexname)) continue;
    out.push(idx.indexdef.replace(/^CREATE (UNIQUE )?INDEX /, "CREATE $1INDEX IF NOT EXISTS ") + ";");
  }
}

// ---------- Views (topologically sorted so a view depending on another view comes after it) ----------
section("VIEWS");
{
  const allViews = await q(
    `select c.oid, n.nspname as schema, c.relname, pg_get_viewdef(c.oid, true) as def
     from pg_class c
     join pg_namespace n on n.oid = c.relnamespace
     where c.relkind = 'v' and n.nspname = any($1)
     order by n.nspname, c.relname`,
    [SCHEMAS]
  );
  totalViews += allViews.length;
  const byOid = new Map(allViews.map((v) => [v.oid, v]));

  // view -> set of view-oids it depends on
  const viewDeps = await q(
    `select distinct r.ev_class as view_oid, d.refobjid as dep_oid
     from pg_rewrite r
     join pg_depend d on d.objid = r.oid
     join pg_class dep_c on dep_c.oid = d.refobjid
     where dep_c.relkind = 'v' and r.ev_class <> d.refobjid`
  );
  const depsByView = new Map();
  for (const row of viewDeps) {
    if (!byOid.has(row.view_oid) || !byOid.has(row.dep_oid)) continue;
    if (!depsByView.has(row.view_oid)) depsByView.set(row.view_oid, new Set());
    depsByView.get(row.view_oid).add(row.dep_oid);
  }

  const visited = new Set();
  const ordered = [];
  const visit = (oid, stack = new Set()) => {
    if (visited.has(oid) || stack.has(oid)) return;
    stack.add(oid);
    for (const dep of depsByView.get(oid) || []) visit(dep, stack);
    stack.delete(oid);
    visited.add(oid);
    ordered.push(oid);
  };
  for (const v of allViews) visit(v.oid);

  for (const oid of ordered) {
    const v = byOid.get(oid);
    out.push(`CREATE OR REPLACE VIEW "${v.schema}"."${v.relname}" AS\n${v.def.trim().replace(/;$/, "")};`);
  }
}

// ---------- Functions ----------
section("FUNCTIONS");
for (const SCHEMA of SCHEMAS) {
  const functions = await q(
    `select p.oid, pg_get_functiondef(p.oid) as def
     from pg_proc p
     join pg_namespace n on n.oid = p.pronamespace
     where n.nspname = $1
     order by p.proname`,
    [SCHEMA]
  );
  totalFunctions += functions.length;
  for (const f of functions) {
    out.push(f.def + ";");
  }
}

// ---------- Triggers ----------
section("TRIGGERS");
for (const SCHEMA of SCHEMAS) {
  const triggers = await q(
    `select tgname, pg_get_triggerdef(t.oid) as def, c.relname as tbl
     from pg_trigger t
     join pg_class c on c.oid = t.tgrelid
     join pg_namespace n on n.oid = c.relnamespace
     where n.nspname = $1 and not t.tgisinternal
     order by tgname`,
    [SCHEMA]
  );
  totalTriggers += triggers.length;
  for (const tr of triggers) {
    out.push(`DROP TRIGGER IF EXISTS "${tr.tgname}" ON "${SCHEMA}"."${tr.tbl}";\n${tr.def};`);
  }
}

// ---------- RLS enable/force + policies ----------
section("ROW LEVEL SECURITY");
for (const SCHEMA of SCHEMAS) {
  const rlsTables = await q(
    `select c.relname, c.relrowsecurity as enabled, c.relforcerowsecurity as forced
     from pg_class c
     join pg_namespace n on n.oid = c.relnamespace
     where c.relkind = 'r' and n.nspname = $1 and c.relrowsecurity
     order by c.relname`,
    [SCHEMA]
  );
  for (const r of rlsTables) {
    out.push(`ALTER TABLE "${SCHEMA}"."${r.relname}" ENABLE ROW LEVEL SECURITY;`);
    if (r.forced) out.push(`ALTER TABLE "${SCHEMA}"."${r.relname}" FORCE ROW LEVEL SECURITY;`);
  }

  const policies = await q(
    `select schemaname, tablename, policyname, permissive, roles, cmd,
            qual, with_check
     from pg_policies
     where schemaname = $1
     order by tablename, policyname`,
    [SCHEMA]
  );
  totalPolicies += policies.length;
  for (const p of policies) {
    let rolesArr = p.roles;
    if (typeof rolesArr === "string") rolesArr = rolesArr.replace(/^\{|\}$/g, "").split(",").filter(Boolean);
    const roles = rolesArr && rolesArr.length ? rolesArr.join(", ") : "public";
    let stmt = `CREATE POLICY "${p.policyname}" ON "${SCHEMA}"."${p.tablename}" AS ${p.permissive} FOR ${p.cmd} TO ${roles}`;
    if (p.qual) stmt += ` USING (${p.qual})`;
    if (p.with_check) stmt += ` WITH CHECK (${p.with_check})`;
    out.push(stmt + ";");
  }
}

await client.end();

const header = `-- Auto-generated schema dump of production schemas: ${SCHEMAS.join(", ")}\n-- Source: introspection via pg_catalog (no pg_dump/Docker) — generated ${new Date().toISOString()}\n-- Target: QA Supabase project bootstrap\n`;
fs.writeFileSync("supabase/qa-bootstrap/schema.sql", header + out.join("\n"));
console.log("Wrote supabase/qa-bootstrap/schema.sql");
console.log("Tables:", totalTables, "Views:", totalViews, "Functions:", totalFunctions, "Triggers:", totalTriggers, "Policies:", totalPolicies);
